server:
  port: 8888

logging:
  path: logs
  file: mylog.log

spring:
  application:
    name: userManager
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.200.2.11:3306/course?useSSL=false
    username: kaifa
    password: kaifa123456
mybatis:
  type-aliases-package: com.course.model
  mapper-locations:
    - mapper/*
